"""Real-time alert WebSocket: rule status changes and high-severity anomalies.

sandbox/promoter.py (which sets APPROVED_PENDING/REJECTED after a sandbox
test) and the ML/ingestion pipeline both run as separate OS processes from
this FastAPI app, with no in-memory link to its WebSocket connections. Alerts
are generated by polling shared state (Postgres, ClickHouse) from a background
task rather than depending on an in-process event/pubsub mechanism, so they
fire regardless of which process caused the change.

The WebSocket endpoint itself is unauthenticated for this MVP — the frontend's
useWebSocket.js connects without a token, since browsers' native WebSocket API
doesn't support custom headers. Revisit if alert content becomes sensitive.
"""

import asyncio
import logging
from datetime import datetime, timezone
from typing import Any

from clickhouse_driver.errors import Error as ClickHouseError
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from sqlalchemy import select
from starlette.concurrency import run_in_threadpool

from core.clickhouse import get_clickhouse_client, to_aware_utc
from core.config import settings
from core.db import AsyncSessionLocal
from models.rule import CandidateRule

logger = logging.getLogger(__name__)

router = APIRouter(tags=["websocket"])

POLL_INTERVAL_SECONDS = 3
MAX_ANOMALIES_PER_POLL = 10


class ConnectionManager:
    """Tracks active WebSocket clients and broadcasts alert messages to all of them."""

    def __init__(self) -> None:
        self._connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket) -> None:
        """Accept and register a new WebSocket client."""
        await websocket.accept()
        self._connections.append(websocket)

    def disconnect(self, websocket: WebSocket) -> None:
        """Remove a client from the active connection list."""
        if websocket in self._connections:
            self._connections.remove(websocket)

    async def broadcast(self, message: dict[str, Any]) -> None:
        """Send a JSON message to every connected client, dropping dead ones."""
        dead = []
        for connection in self._connections:
            try:
                await connection.send_json(message)
            except Exception:
                # A dead client can fail in several distinct ways (closed
                # connection, protocol error, network drop) — all of them
                # mean the same thing here: drop it. Scoped to one send call.
                dead.append(connection)
        for connection in dead:
            self.disconnect(connection)


manager = ConnectionManager()


@router.websocket("/api/v1/ws/alerts")
async def alerts_websocket(websocket: WebSocket) -> None:
    """Real-time alert stream: rule status changes and high-severity anomalies."""
    await manager.connect(websocket)
    try:
        while True:
            # Clients don't send anything meaningful; this just blocks until
            # the client disconnects, so we notice and clean up.
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(websocket)


def _fetch_new_anomalies(since: datetime, threshold: float) -> list[dict[str, Any]]:
    """Query traffic_events for newly-seen rows above the alert threshold.

    Synchronous — callers must run this via run_in_threadpool.
    """
    client = get_clickhouse_client()
    columns = ["timestamp", "src_ip", "dst_ip", "anomaly_score"]
    rows = client.execute(
        f"SELECT {', '.join(columns)} FROM traffic_events "
        "WHERE timestamp > %(since)s AND anomaly_score > %(threshold)s "
        "ORDER BY timestamp ASC",
        {"since": since, "threshold": threshold},
    )
    return [dict(zip(columns, row, strict=True)) for row in rows]


async def poll_and_broadcast_alerts() -> None:
    """Background task: broadcasts an alert for rule status changes and new anomalies."""
    last_rule_update = datetime.now(timezone.utc)
    last_anomaly_timestamp = datetime.now(timezone.utc)

    while True:
        await asyncio.sleep(POLL_INTERVAL_SECONDS)

        try:
            async with AsyncSessionLocal() as db:
                result = await db.execute(
                    select(CandidateRule)
                    .where(CandidateRule.updated_at > last_rule_update)
                    .order_by(CandidateRule.updated_at.asc())
                )
                changed_rules = result.scalars().all()
        except Exception as e:
            # This is a long-running background task, not a request handler —
            # a transient DB hiccup must log and retry next cycle, never crash
            # the poller permanently.
            logger.error(f"Rule status poll failed: {e}")
            changed_rules = []

        for rule in changed_rules:
            last_rule_update = max(last_rule_update, to_aware_utc(rule.updated_at))
            await manager.broadcast(
                {
                    "type": "rule_status_change",
                    "message": f"Rule {rule.id} is now {rule.status}",
                    "rule_id": str(rule.id),
                    "status": rule.status,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            )

        try:
            new_anomalies = await run_in_threadpool(
                _fetch_new_anomalies, last_anomaly_timestamp, settings.ANOMALY_ALERT_THRESHOLD
            )
        except ClickHouseError as e:
            logger.error(f"Anomaly poll failed: {e}")
            new_anomalies = []

        for row in new_anomalies[:MAX_ANOMALIES_PER_POLL]:
            last_anomaly_timestamp = max(
                last_anomaly_timestamp, to_aware_utc(row["timestamp"])
            )
            await manager.broadcast(
                {
                    "type": "anomaly",
                    "message": (
                        f"High-severity anomaly from {row['src_ip']} to {row['dst_ip']} "
                        f"(score {row['anomaly_score']:.2f})"
                    ),
                    "src_ip": row["src_ip"],
                    "dst_ip": row["dst_ip"],
                    "anomaly_score": row["anomaly_score"],
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
            )
